version: '3.9'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: "10"

# shared environment variables between wordpress and wp-cli
x-wp-env:
  &wordpress-environment
  WORDPRESS_DB_HOST: db:3306
  WORDPRESS_DB_NAME: $MYSQL_DATABASE
  WORDPRESS_DB_USER: $MYSQL_USER
  WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD

services:

  # MARIADB ============================================================================================ #

  mariadb:
    container_name: mariadb
    image: mariadb:10.5.9
    profiles:
      - mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    logging: *default-logging
    networks:
      wp-net:
        aliases:
          - db

  # MYSQL ============================================================================================== #

  mysql:
    container_name: mysql
    image: mysql:8.0.23
    profiles:
      - mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    cap_add:
      - SYS_NICE # CAP_SYS_NICE, fix mbind permission issue
    logging: *default-logging
    networks:
      wp-net:
        aliases:
          - db

  # WORDPRESS ========================================================================================== #

  wordpress:
    container_name: wordpress
    hostname: "${DOMAIN_NAME}" # avoid warning from apache
    image: wordpress:5.7.0-php7.4-apache
    #depends_on:
      #- mysql
      #- mariadb
    expose:
      - "80"
    volumes:
      - ./apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./wp-data:/var/www/html
    restart: always
    environment:
      << : *wordpress-environment
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DB_COLLATE: utf8mb4_unicode_520_ci
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_WP_SITEURL: "http://${DOMAIN_NAME}" # won't work with existed site
      WORDPRESS_WP_HOME: "http://${DOMAIN_NAME}" # won't work with existed site
    logging: *default-logging
    networks:
      wp-net: {}

  # NGINX ============================================================================================== #

  nginx:
    container_name: nginx
    image: nginx:1.19.9
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl.conf.template:/etc/nginx/templates/ssl.conf.template
      - ./cert/server.crt:/etc/ssl/certs/server.crt
      - ./cert/server.key:/etc/ssl/private/server.key
    working_dir: /etc/nginx
    # disabled nginx access log to avoid duplication with apache2
    logging: #*default-logging
      driver: none
    networks:
      wp-net: {}

  # WP-CLI ============================================================================================= #

  # TODO automate wp installation
  wp-cli:
    container_name: wp-cli
    image: wordpress:cli-2.4.0-php7.4
    profiles:
      - auto-config # for now, prevent this container from running automatically
    depends_on:
      - wordpress
    volumes:
      - ./wp-data:/var/www/html # shared with wordpress
    user: "33"
    command: >
      wp core install
      --path="/var/www/html"
      --url="http://${DOMAIN_NAME}"
      --title="Deathnote"
      --admin_user=hino
      --admin_password=password
      --admin_email=hino@hino.io
      --skip-email
    environment: *wordpress-environment
    logging: *default-logging
    networks:
      wp-net: {}

  # END ================================================================================================ #

volumes:
  mariadb-data: {}
  mysql-data: {}

networks:
  wp-net: {}

