version: '3.8'

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: "10"

services:
  db:
    container_name: db
    image: mariadb:10.2.33
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    logging: *default-logging

  wordpress:
    container_name: wordpress
    hostname: "${DOMAIN_NAME}" # avoid warning from apache
    image: wordpress:5.7-php7.4-apache
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./wp-data:/var/www/html
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DB_COLLATE: utf8mb4_unicode_520_ci
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_WP_SITEURL: "http://${DOMAIN_NAME}" # won't work with existed site
      WORDPRESS_WP_HOME: "http://${DOMAIN_NAME}" # won't work with existed site
    logging: *default-logging

volumes:
  db-data: {}

